stages:
  - test
  - publish

unit test project:
  stage: test
  script:
    - npm install
    - npm test -- --passWithNoTests
  tags:
    - neoco

publish project:
  stage: publish
  script:
    - npm install
    - npm run build
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm publish --access public
  only:
    - master
  when: manual
  tags:
    - neoco
